### ISSUE TITLE
Only on Azj-Kahet map

### ISSUE THREAD

**Issue by cyberox** [NumyAddon/HandyNotes_RumorMap#1]
This is a great addon, and I use it a lot.
The only problem I encounter is that the icons are only visible on the Azj-Kahet map and not on the City of Threads detail map. Could it be possible to add them there as well?

**Comment by Numynum** [comment]
Yup, should be coming soon ™️ 🙂 (probably today or tomorrow)

**Comment by Numynum** [comment]
done in latest version 👍
